package com.blastlong.pmh.gui.util;

import java.util.HashMap;
import java.util.Map;

public class ItemNameTranslator {
    private static final HashMap<String, String> itemNameTranslationTable = new HashMap<>() {{
        put("CARROT", "당근");
        put("POTATO", "감자");
        put("SUGAR_CANE", "사탕수수");
        put("BLAZE_ROD", "블레이즈 막대기");
        put("NETHER_WART", "네더 사마귀");
        put("WHEAT", "밀");
        put("ENCHANTED_BOOK_SILK_TOUCH", "인챈트 북 - 섬세한 손길");
        put("ENCHANTED_BOOK_ARROW_FIRE", "인챈트 북 - 화염");
        put("ENCHANTED_BOOK_CHANNELING", "인챈트 북 - 집전");
        put("BONE_BLOCK", "뼈블럭");
        put("LEATHER", "가죽");
        put("ENCHANTED_BOOK_PROTECTION_ENVIRONMENTAL", "보호");
        put("ENCHANTED_BOOK_ARROW_INFINITE", "무한");
        put("GLOWSTONE", "발광석");
        put("WHITE_CANDLE", "하얀색 초");
        put("CANDLE", "초");
        put("SHULKER_BOX", "셜커상자");
        put("HAY_BLOCK", "건초더미");
        put("MELON_SLICE", "수박");
        put("ENCHANTED_BOOK_SWIFT_SNEAK", "인챈트 북 - 신속한 잠행");
        put("YELLOW_STAINED_GLASS_PANE", "노란색 색유리 판");
        put("DIAMOND_BLOCK", "다이아몬드 블럭");
        put("PINK_STAINED_GLASS_PANE", "분홍색 색유리 판");
        put("RED_STAINED_GLASS_PANE", "빨간색 색유리 판");
        put("BLACK_STAINED_GLASS_PANE", "검정색 색유리 판");
        put("NETHERITE_PICKAXE", "네더라이트 곡괭이");
        put("IRON_LEGGINGS", "철 레깅스");
        put("EMERALD", "에메랄드");
        put("SHULKER_SHELL", "셜커 껍데기");
        put("SEA_LANTERN", "바다랜턴");
        put("ELYTRA", "겉날개");
        put("GUNPOWDER", "화약");
        put("SPONGE", "스펀지");
        put("WHITE_STAINED_GLASS_PANE", "하얀색 색유리 판");
        put("GHAST_TEAR", "가스트 눈물");
        put("ENCHANTED_BOOK_MENDING", "인챈트 북 - 수선");
        put("EGG", "달걀");
        put("DRIED_KELP_BLOCK", "말린 켈프 블럭");
        put("APPLE", "사과");
        put("COOKIE", "쿠키");
        put("PUMPKIN", "호박");
        put("SUGAR", "설탕");
        put("AMETHYST_SHARD", "자수정 조각");
        put("MOSS_BLOCK", "이끼 블럭");
        put("CHERRY_SAPLING", "벚나무 묘목");
        put("ORANGE_SHULKER_BOX", "주황색 셜커 상자");
        put("QUARTZ_BLOCK", "석영 블럭");
        put("CHERRY_LEAVES", "벚나무 잎");
        put("GREEN_SHULKER_BOX", "연두색 셜커 상자");
        put("MANGROVE_LOG", "맹그로브 원목");
        put("CHERRY_LOG", "벚나무 원목");
        put("YELLOW_SHULKER_BOX", "노란색 셜커 상자");
        put("ENDER_CHEST", "엔더상자");
        put("END_ROD", "엔더 막대기");
        put("DRAGON_HEAD", "드래곤 머리");
        put("MAGENTA_DYE", "자홍색 염료");
        put("BOOKSHELF", "책장");
        put("RED_DYE", "빨간색 염료");
        put("ORANGE_DYE", "주황색 염료");
        put("YELLOW_DYE", "노란색 염료");
        put("LIME_DYE", "연두색 염료");
        put("GREEN_DYE", "초록색 염료");
        put("ENDER_PEARL", "엔더진주");
        put("CYAN_DYE", "청록색 염료");
        put("LIGHT_BLUE_DYE", "하늘색 염료");
        put("BLUE_DYE", "파란색 염료");
        put("PURPLE_DYE", "보라색 염료");
        put("PINK_DYE", "분홍색 염료");
        put("BROWN_DYE", "갈색 염료");
        put("WHITE_DYE", "하얀색 염료");
        put("LIGHT_GRAY_DYE", "회백색 염료");
        put("GRAY_DYE", "회색 염료");
        put("BLACK_DYE", "검정색 염료");
        put("MUSIC_DISC_CAT", "음반 - cat");
        put("MUSIC_DISC_13", "음반 - 13");
        put("DIAMOND_LEGGINGS", "다이아몬드 레깅스");
        put("ENCHANTED_BOOK_DIG_SPEED", "인챈트 북 - 효율");
        put("ENCHANTED_BOOK_DURABILITY", "인챈트 북 - 내구성");
        put("BLUE_STAINED_GLASS_PANE", "파란색 색유리 판");
        put("PINK_SHULKER_BOX", "분홍색 셜커 상자");
        put("DIAMOND", "다이아몬드");
        put("IRON_BLOCK", "철 블럭");
        put("DIAMOND_HELMET", "다이아몬드 헬멧");
        put("DIAMOND_CHESTPLATE", "다이아몬드 흉갑");
        put("DIAMOND_SWORD", "다이아몬드 검");
        put("FIREWORK_ROCKET", "폭죽");
        put("RED_SHULKER_BOX", "빨간색 셜커 상자");
        put("BEACON", "신호기");
        put("BARREL", "통");
        put("ENCHANTED_BOOK_DAMAGE_ALL", "날카로움");
        put("NETHERITE_UPGRADE_SMITHING_TEMPLATE", "대장장이 형판 - 네더라이트 강화");
        put("RIB_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 갈비뼈");
        put("PRISMARINE_SHARD", "프리즈마린 조각");
        put("EYE_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 눈");
        put("SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 돼지코");
        put("SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 보초");
        put("GLASS_PANE", "유리 판");
        put("CHAIN", "사슬");
        put("DIAMOND_HOE", "다이아몬드 괭이");
        put("NETHERITE_SCRAP", "네더라이트 파편");
        put("FISHING_ROD", "낚싯대");
        put("NETHERITE_SWORD", "네더라이트 검");
        put("NETHERITE_HELMET", "네더라이트 헬멧");
        put("NETHERITE_CHESTPLATE", "네더라이트 흉갑");
        put("NETHERITE_SHOVEL", "네더라이트 삽");
        put("NETHERITE_LEGGINGS", "네더라이트 레깅스");
        put("NETHERITE_BOOTS", "네더라이트 부츠");
        put("DIAMOND_HORSE_ARMOR", "다이아몬드 말 갑옷");
        put("STRING", "실");
        put("GLOW_INK_SAC", "발광 먹물 주머니");
        put("GOLD_INGOT", "금 주괴");
        put("LAPIS_LAZULI", "청금석");
        put("NAME_TAG", "이름표");
        put("LIGHT_BLUE_STAINED_GLASS_PANE", "하늘색 색유리 판");
        put("LIGHT_GRAY_STAINED_GLASS_PANE", "회백색 색유리 판");
        put("COAST_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 해안");
        put("SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 첨탑");
        put("DUNE_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 사구");
        put("WARD_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 파수");
        put("WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 길잡이");
        put("RAISER_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 사육사");
        put("SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 조형가");
        put("TIDE_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 물결");
        put("SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE", "대장장이 형판 - 고요");
        put("DIAMOND_PICKAXE", "다이아몬드 곡괭이");
        put("NETHERITE_INGOT", "네더라이트 주괴");
        put("TRIDENT", "삼지창");
    }};

    public static String translate(String content) {
        if (itemNameTranslationTable.containsKey(content)) {
            return itemNameTranslationTable.get(content);
        }
        return content;
    }
}
